/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *groupBox;
    QLabel *label_6;
    QComboBox *comboBoxUart1;
    QLabel *label_7;
    QLineEdit *lineEditBaudRate1;
    QPushButton *pushButtonOpenUart1;
    QLabel *label_28;
    QLineEdit *lineEditBaudRate2;
    QComboBox *comboBoxUart2;
    QLabel *label_29;
    QPushButton *pushButtonOpenUart2;
    QSlider *horizontalSlider;
    QGroupBox *groupBoxAlarm;
    QLabel *label_8;
    QSlider *hSliderWindSpeedLimit;
    QLabel *labelWindSpeedLimit;
    QLabel *labelAlarm;
    QLabel *label_19;
    QSlider *hSliderTemperatureLimit;
    QLabel *labelTemperatureLimit;
    QSlider *hSliderIlluminationLimit;
    QLabel *labelIlluminationLimit;
    QLabel *label_20;
    QGroupBox *groupBox_3;
    QLabel *labelWindDirectionIcon;
    QLabel *label;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QProgressBar *progressBarHumidity;
    QLabel *label_2;
    QProgressBar *progressBarTemperature;
    QProgressBar *progressBarPressure;
    QProgressBar *progressBarIllumination;
    QProgressBar *progressBarWindSpeed;
    QProgressBar *progressBarAltitude;
    QLabel *labelHumidity;
    QLabel *labelTemperature;
    QLabel *labelPressure;
    QLabel *labelIllumination;
    QLabel *labelWindSpeed;
    QLabel *labelAltitude;
    QLabel *labelWindDirection;
    QLabel *label_5;
    QLabel *label_18;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_30;
    QLabel *label_31;
    QGroupBox *groupBox_4;
    QRadioButton *radioButtonManualMode;
    QRadioButton *radioButtonAutoMode;
    QPushButton *pushButtonGetHardwareData;
    QPushButton *pushButtonGetRandomData;
    QPushButton *pushButtonGetInputData;
    QTextEdit *textEditLog;
    QGroupBox *groupBoxHTTP;
    QLineEdit *lineEditDeviceID;
    QLineEdit *lineEditAPIKey;
    QLabel *label_54;
    QLabel *label_55;
    QGroupBox *groupBoxTCP;
    QLineEdit *lineEditProductID;
    QLineEdit *lineEditAuthCode;
    QLabel *label_56;
    QLabel *label_57;
    QLineEdit *lineEditScriptName;
    QLabel *label_58;
    QPushButton *pushButtonClearLog;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1011, 780);
        QFont font;
        font.setPointSize(9);
        MainWindow->setFont(font);
        MainWindow->setAutoFillBackground(false);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 20, 631, 141));
        groupBox->setFont(font);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 30, 121, 31));
        label_6->setFont(font);
        label_6->setAlignment(Qt::AlignCenter);
        comboBoxUart1 = new QComboBox(groupBox);
        comboBoxUart1->setObjectName(QString::fromUtf8("comboBoxUart1"));
        comboBoxUart1->setGeometry(QRect(130, 30, 121, 32));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(290, 30, 171, 31));
        label_7->setFont(font);
        label_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEditBaudRate1 = new QLineEdit(groupBox);
        lineEditBaudRate1->setObjectName(QString::fromUtf8("lineEditBaudRate1"));
        lineEditBaudRate1->setGeometry(QRect(350, 30, 71, 31));
        lineEditBaudRate1->setFont(font);
        lineEditBaudRate1->setAlignment(Qt::AlignCenter);
        pushButtonOpenUart1 = new QPushButton(groupBox);
        pushButtonOpenUart1->setObjectName(QString::fromUtf8("pushButtonOpenUart1"));
        pushButtonOpenUart1->setGeometry(QRect(490, 30, 121, 31));
        pushButtonOpenUart1->setFont(font);
        label_28 = new QLabel(groupBox);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(290, 80, 171, 31));
        label_28->setFont(font);
        label_28->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEditBaudRate2 = new QLineEdit(groupBox);
        lineEditBaudRate2->setObjectName(QString::fromUtf8("lineEditBaudRate2"));
        lineEditBaudRate2->setGeometry(QRect(350, 80, 71, 31));
        lineEditBaudRate2->setFont(font);
        lineEditBaudRate2->setAlignment(Qt::AlignCenter);
        comboBoxUart2 = new QComboBox(groupBox);
        comboBoxUart2->setObjectName(QString::fromUtf8("comboBoxUart2"));
        comboBoxUart2->setGeometry(QRect(130, 80, 121, 32));
        label_29 = new QLabel(groupBox);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 80, 121, 31));
        label_29->setFont(font);
        label_29->setAlignment(Qt::AlignCenter);
        pushButtonOpenUart2 = new QPushButton(groupBox);
        pushButtonOpenUart2->setObjectName(QString::fromUtf8("pushButtonOpenUart2"));
        pushButtonOpenUart2->setGeometry(QRect(490, 80, 121, 31));
        pushButtonOpenUart2->setFont(font);
        horizontalSlider = new QSlider(centralwidget);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(-340, 260, 160, 31));
        horizontalSlider->setOrientation(Qt::Horizontal);
        groupBoxAlarm = new QGroupBox(centralwidget);
        groupBoxAlarm->setObjectName(QString::fromUtf8("groupBoxAlarm"));
        groupBoxAlarm->setGeometry(QRect(10, 470, 481, 161));
        groupBoxAlarm->setFont(font);
        groupBoxAlarm->setCheckable(true);
        label_8 = new QLabel(groupBoxAlarm);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(40, 30, 111, 41));
        label_8->setFont(font);
        label_8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        hSliderWindSpeedLimit = new QSlider(groupBoxAlarm);
        hSliderWindSpeedLimit->setObjectName(QString::fromUtf8("hSliderWindSpeedLimit"));
        hSliderWindSpeedLimit->setGeometry(QRect(160, 40, 171, 25));
        hSliderWindSpeedLimit->setMaximum(20);
        hSliderWindSpeedLimit->setPageStep(5);
        hSliderWindSpeedLimit->setValue(3);
        hSliderWindSpeedLimit->setOrientation(Qt::Horizontal);
        labelWindSpeedLimit = new QLabel(groupBoxAlarm);
        labelWindSpeedLimit->setObjectName(QString::fromUtf8("labelWindSpeedLimit"));
        labelWindSpeedLimit->setGeometry(QRect(340, 30, 41, 41));
        labelWindSpeedLimit->setFont(font);
        labelWindSpeedLimit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelAlarm = new QLabel(groupBoxAlarm);
        labelAlarm->setObjectName(QString::fromUtf8("labelAlarm"));
        labelAlarm->setGeometry(QRect(390, 60, 71, 61));
        labelAlarm->setPixmap(QPixmap(QString::fromUtf8("res/warning.png")));
        labelAlarm->setScaledContents(true);
        label_19 = new QLabel(groupBoxAlarm);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(40, 70, 101, 41));
        label_19->setFont(font);
        label_19->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        hSliderTemperatureLimit = new QSlider(groupBoxAlarm);
        hSliderTemperatureLimit->setObjectName(QString::fromUtf8("hSliderTemperatureLimit"));
        hSliderTemperatureLimit->setGeometry(QRect(160, 80, 171, 25));
        hSliderTemperatureLimit->setMinimum(-20);
        hSliderTemperatureLimit->setMaximum(45);
        hSliderTemperatureLimit->setPageStep(5);
        hSliderTemperatureLimit->setValue(25);
        hSliderTemperatureLimit->setOrientation(Qt::Horizontal);
        labelTemperatureLimit = new QLabel(groupBoxAlarm);
        labelTemperatureLimit->setObjectName(QString::fromUtf8("labelTemperatureLimit"));
        labelTemperatureLimit->setGeometry(QRect(340, 70, 41, 41));
        labelTemperatureLimit->setFont(font);
        labelTemperatureLimit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        hSliderIlluminationLimit = new QSlider(groupBoxAlarm);
        hSliderIlluminationLimit->setObjectName(QString::fromUtf8("hSliderIlluminationLimit"));
        hSliderIlluminationLimit->setGeometry(QRect(160, 120, 171, 25));
        hSliderIlluminationLimit->setMinimum(0);
        hSliderIlluminationLimit->setMaximum(200);
        hSliderIlluminationLimit->setPageStep(5);
        hSliderIlluminationLimit->setValue(30);
        hSliderIlluminationLimit->setOrientation(Qt::Horizontal);
        labelIlluminationLimit = new QLabel(groupBoxAlarm);
        labelIlluminationLimit->setObjectName(QString::fromUtf8("labelIlluminationLimit"));
        labelIlluminationLimit->setGeometry(QRect(340, 110, 61, 41));
        labelIlluminationLimit->setFont(font);
        labelIlluminationLimit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_20 = new QLabel(groupBoxAlarm);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(40, 110, 111, 41));
        label_20->setFont(font);
        label_20->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_20->raise();
        label_8->raise();
        hSliderWindSpeedLimit->raise();
        labelWindSpeedLimit->raise();
        labelAlarm->raise();
        label_19->raise();
        hSliderTemperatureLimit->raise();
        labelTemperatureLimit->raise();
        hSliderIlluminationLimit->raise();
        labelIlluminationLimit->raise();
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 180, 991, 271));
        groupBox_3->setFont(font);
        labelWindDirectionIcon = new QLabel(groupBox_3);
        labelWindDirectionIcon->setObjectName(QString::fromUtf8("labelWindDirectionIcon"));
        labelWindDirectionIcon->setGeometry(QRect(740, 50, 171, 151));
        QFont font1;
        font1.setPointSize(15);
        labelWindDirectionIcon->setFont(font1);
        labelWindDirectionIcon->setPixmap(QPixmap(QString::fromUtf8("res/0.png")));
        labelWindDirectionIcon->setScaledContents(true);
        labelWindDirectionIcon->setAlignment(Qt::AlignCenter);
        labelWindDirectionIcon->setWordWrap(false);
        label = new QLabel(groupBox_3);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(50, 20, 150, 41));
        label->setFont(font);
        label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(50, 60, 150, 41));
        label_9->setFont(font);
        label_9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(50, 180, 150, 41));
        label_10->setFont(font);
        label_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(groupBox_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(50, 100, 150, 41));
        label_11->setFont(font);
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(50, 140, 150, 41));
        label_12->setFont(font);
        label_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(groupBox_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(50, 220, 150, 41));
        label_13->setFont(font);
        label_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_14 = new QLabel(groupBox_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(790, 220, 71, 41));
        label_14->setFont(font);
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        progressBarHumidity = new QProgressBar(groupBox_3);
        progressBarHumidity->setObjectName(QString::fromUtf8("progressBarHumidity"));
        progressBarHumidity->setGeometry(QRect(300, 30, 271, 23));
        progressBarHumidity->setValue(50);
        progressBarHumidity->setTextVisible(false);
        label_2 = new QLabel(groupBox_3);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(240, 30, 41, 23));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        progressBarTemperature = new QProgressBar(groupBox_3);
        progressBarTemperature->setObjectName(QString::fromUtf8("progressBarTemperature"));
        progressBarTemperature->setGeometry(QRect(300, 70, 271, 23));
        progressBarTemperature->setMinimum(-20);
        progressBarTemperature->setMaximum(45);
        progressBarTemperature->setValue(25);
        progressBarTemperature->setTextVisible(false);
        progressBarPressure = new QProgressBar(groupBox_3);
        progressBarPressure->setObjectName(QString::fromUtf8("progressBarPressure"));
        progressBarPressure->setGeometry(QRect(300, 110, 271, 23));
        progressBarPressure->setMinimum(90);
        progressBarPressure->setMaximum(110);
        progressBarPressure->setValue(101);
        progressBarPressure->setTextVisible(false);
        progressBarIllumination = new QProgressBar(groupBox_3);
        progressBarIllumination->setObjectName(QString::fromUtf8("progressBarIllumination"));
        progressBarIllumination->setGeometry(QRect(300, 150, 271, 23));
        progressBarIllumination->setMaximum(200);
        progressBarIllumination->setValue(50);
        progressBarIllumination->setTextVisible(false);
        progressBarWindSpeed = new QProgressBar(groupBox_3);
        progressBarWindSpeed->setObjectName(QString::fromUtf8("progressBarWindSpeed"));
        progressBarWindSpeed->setGeometry(QRect(300, 230, 271, 23));
        progressBarWindSpeed->setMaximum(20);
        progressBarWindSpeed->setValue(2);
        progressBarWindSpeed->setTextVisible(false);
        progressBarAltitude = new QProgressBar(groupBox_3);
        progressBarAltitude->setObjectName(QString::fromUtf8("progressBarAltitude"));
        progressBarAltitude->setGeometry(QRect(300, 190, 271, 23));
        progressBarAltitude->setMinimum(-200);
        progressBarAltitude->setMaximum(1000);
        progressBarAltitude->setValue(100);
        progressBarAltitude->setTextVisible(false);
        labelHumidity = new QLabel(groupBox_3);
        labelHumidity->setObjectName(QString::fromUtf8("labelHumidity"));
        labelHumidity->setGeometry(QRect(90, 20, 61, 41));
        labelHumidity->setFont(font);
        labelHumidity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelTemperature = new QLabel(groupBox_3);
        labelTemperature->setObjectName(QString::fromUtf8("labelTemperature"));
        labelTemperature->setGeometry(QRect(90, 60, 61, 41));
        labelTemperature->setFont(font);
        labelTemperature->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelPressure = new QLabel(groupBox_3);
        labelPressure->setObjectName(QString::fromUtf8("labelPressure"));
        labelPressure->setGeometry(QRect(90, 100, 61, 41));
        labelPressure->setFont(font);
        labelPressure->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelIllumination = new QLabel(groupBox_3);
        labelIllumination->setObjectName(QString::fromUtf8("labelIllumination"));
        labelIllumination->setGeometry(QRect(80, 140, 71, 41));
        labelIllumination->setFont(font);
        labelIllumination->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelWindSpeed = new QLabel(groupBox_3);
        labelWindSpeed->setObjectName(QString::fromUtf8("labelWindSpeed"));
        labelWindSpeed->setGeometry(QRect(100, 220, 51, 41));
        labelWindSpeed->setFont(font);
        labelWindSpeed->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelAltitude = new QLabel(groupBox_3);
        labelAltitude->setObjectName(QString::fromUtf8("labelAltitude"));
        labelAltitude->setGeometry(QRect(80, 180, 71, 41));
        labelAltitude->setFont(font);
        labelAltitude->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelWindDirection = new QLabel(groupBox_3);
        labelWindDirection->setObjectName(QString::fromUtf8("labelWindDirection"));
        labelWindDirection->setGeometry(QRect(830, 220, 51, 41));
        labelWindDirection->setFont(font);
        labelWindDirection->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(groupBox_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(590, 30, 81, 23));
        label_5->setFont(font);
        label_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_18 = new QLabel(groupBox_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(240, 70, 41, 23));
        label_18->setFont(font);
        label_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_21 = new QLabel(groupBox_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(240, 150, 41, 23));
        label_21->setFont(font);
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(groupBox_3);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(240, 110, 41, 23));
        label_22->setFont(font);
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(groupBox_3);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(240, 230, 41, 23));
        label_23->setFont(font);
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_24 = new QLabel(groupBox_3);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(240, 190, 41, 23));
        label_24->setFont(font);
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_25 = new QLabel(groupBox_3);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(590, 70, 81, 23));
        label_25->setFont(font);
        label_25->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_26 = new QLabel(groupBox_3);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(590, 110, 81, 23));
        label_26->setFont(font);
        label_26->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_27 = new QLabel(groupBox_3);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(590, 150, 81, 23));
        label_27->setFont(font);
        label_27->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_30 = new QLabel(groupBox_3);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(590, 190, 81, 23));
        label_30->setFont(font);
        label_30->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31 = new QLabel(groupBox_3);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(590, 230, 81, 23));
        label_31->setFont(font);
        label_31->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2->raise();
        labelWindDirectionIcon->raise();
        label->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        progressBarHumidity->raise();
        progressBarTemperature->raise();
        progressBarPressure->raise();
        progressBarIllumination->raise();
        progressBarWindSpeed->raise();
        progressBarAltitude->raise();
        labelHumidity->raise();
        labelTemperature->raise();
        labelPressure->raise();
        labelIllumination->raise();
        labelWindSpeed->raise();
        labelAltitude->raise();
        labelWindDirection->raise();
        label_5->raise();
        label_18->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_30->raise();
        label_31->raise();
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(650, 20, 351, 141));
        groupBox_4->setFont(font);
        radioButtonManualMode = new QRadioButton(groupBox_4);
        radioButtonManualMode->setObjectName(QString::fromUtf8("radioButtonManualMode"));
        radioButtonManualMode->setGeometry(QRect(20, 40, 141, 31));
        radioButtonManualMode->setChecked(true);
        radioButtonAutoMode = new QRadioButton(groupBox_4);
        radioButtonAutoMode->setObjectName(QString::fromUtf8("radioButtonAutoMode"));
        radioButtonAutoMode->setGeometry(QRect(20, 80, 141, 31));
        pushButtonGetHardwareData = new QPushButton(groupBox_4);
        pushButtonGetHardwareData->setObjectName(QString::fromUtf8("pushButtonGetHardwareData"));
        pushButtonGetHardwareData->setGeometry(QRect(160, 20, 180, 30));
        pushButtonGetHardwareData->setFont(font);
        pushButtonGetRandomData = new QPushButton(groupBox_4);
        pushButtonGetRandomData->setObjectName(QString::fromUtf8("pushButtonGetRandomData"));
        pushButtonGetRandomData->setGeometry(QRect(160, 60, 180, 30));
        pushButtonGetRandomData->setFont(font);
        pushButtonGetInputData = new QPushButton(groupBox_4);
        pushButtonGetInputData->setObjectName(QString::fromUtf8("pushButtonGetInputData"));
        pushButtonGetInputData->setGeometry(QRect(160, 100, 180, 30));
        pushButtonGetInputData->setFont(font);
        textEditLog = new QTextEdit(centralwidget);
        textEditLog->setObjectName(QString::fromUtf8("textEditLog"));
        textEditLog->setGeometry(QRect(10, 650, 911, 121));
        groupBoxHTTP = new QGroupBox(centralwidget);
        groupBoxHTTP->setObjectName(QString::fromUtf8("groupBoxHTTP"));
        groupBoxHTTP->setGeometry(QRect(760, 470, 241, 161));
        groupBoxHTTP->setCheckable(true);
        groupBoxHTTP->setChecked(false);
        lineEditDeviceID = new QLineEdit(groupBoxHTTP);
        lineEditDeviceID->setObjectName(QString::fromUtf8("lineEditDeviceID"));
        lineEditDeviceID->setGeometry(QRect(110, 30, 113, 31));
        lineEditAPIKey = new QLineEdit(groupBoxHTTP);
        lineEditAPIKey->setObjectName(QString::fromUtf8("lineEditAPIKey"));
        lineEditAPIKey->setGeometry(QRect(110, 70, 113, 31));
        label_54 = new QLabel(groupBoxHTTP);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(30, 30, 71, 31));
        label_54->setFont(font);
        label_54->setAlignment(Qt::AlignCenter);
        label_55 = new QLabel(groupBoxHTTP);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(30, 70, 71, 31));
        label_55->setFont(font);
        label_55->setAlignment(Qt::AlignCenter);
        groupBoxTCP = new QGroupBox(centralwidget);
        groupBoxTCP->setObjectName(QString::fromUtf8("groupBoxTCP"));
        groupBoxTCP->setGeometry(QRect(500, 470, 251, 161));
        groupBoxTCP->setCheckable(true);
        groupBoxTCP->setChecked(false);
        lineEditProductID = new QLineEdit(groupBoxTCP);
        lineEditProductID->setObjectName(QString::fromUtf8("lineEditProductID"));
        lineEditProductID->setGeometry(QRect(110, 30, 131, 31));
        lineEditAuthCode = new QLineEdit(groupBoxTCP);
        lineEditAuthCode->setObjectName(QString::fromUtf8("lineEditAuthCode"));
        lineEditAuthCode->setGeometry(QRect(110, 70, 131, 31));
        label_56 = new QLabel(groupBoxTCP);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(30, 70, 71, 31));
        label_56->setFont(font);
        label_56->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_57 = new QLabel(groupBoxTCP);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(30, 30, 71, 31));
        label_57->setFont(font);
        label_57->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEditScriptName = new QLineEdit(groupBoxTCP);
        lineEditScriptName->setObjectName(QString::fromUtf8("lineEditScriptName"));
        lineEditScriptName->setGeometry(QRect(110, 110, 131, 31));
        label_58 = new QLabel(groupBoxTCP);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(30, 110, 81, 31));
        label_58->setFont(font);
        label_58->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonClearLog = new QPushButton(centralwidget);
        pushButtonClearLog->setObjectName(QString::fromUtf8("pushButtonClearLog"));
        pushButtonClearLog->setGeometry(QRect(930, 650, 71, 121));
        MainWindow->setCentralWidget(centralwidget);
        groupBox_3->raise();
        groupBoxAlarm->raise();
        groupBox->raise();
        horizontalSlider->raise();
        groupBox_4->raise();
        textEditLog->raise();
        groupBoxHTTP->raise();
        groupBoxTCP->raise();
        pushButtonClearLog->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "\347\256\200\346\230\223\346\260\224\350\261\241\347\253\231V0.1-\351\207\221\351\231\265\347\247\221\346\212\200\345\255\246\351\231\242", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindow", "\344\270\262\345\217\243\346\223\215\344\275\234", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "\346\260\224\350\261\241\344\277\241\346\201\257\344\270\262\345\217\243\357\274\232", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "\346\263\242\347\211\271\347\216\207\357\274\232          bps", nullptr));
        lineEditBaudRate1->setText(QCoreApplication::translate("MainWindow", "9600", nullptr));
        pushButtonOpenUart1->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\2431", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "\346\263\242\347\211\271\347\216\207\357\274\232          bps", nullptr));
        lineEditBaudRate2->setText(QCoreApplication::translate("MainWindow", "4800", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "\351\243\216\351\200\237\351\243\216\345\220\221\344\270\262\345\217\243\357\274\232", nullptr));
        pushButtonOpenUart2->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\2432", nullptr));
        groupBoxAlarm->setTitle(QCoreApplication::translate("MainWindow", "\346\212\245\350\255\246\346\216\247\345\210\266", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "\351\243\216\351\200\237\344\270\212\351\231\220(m/s)", nullptr));
        labelWindSpeedLimit->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        labelAlarm->setText(QString());
        label_19->setText(QCoreApplication::translate("MainWindow", "\346\270\251\345\272\246\344\270\212\351\231\220(\342\204\203)", nullptr));
        labelTemperatureLimit->setText(QCoreApplication::translate("MainWindow", "25", nullptr));
        labelIlluminationLimit->setText(QCoreApplication::translate("MainWindow", "30", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "\347\205\247\345\272\246\344\270\212\351\231\220(klux)", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindow", "\346\260\224\350\261\241\344\277\241\346\201\257", nullptr));
        labelWindDirectionIcon->setText(QString());
        label->setText(QCoreApplication::translate("MainWindow", "\346\271\277\345\272\246\357\274\232        %RH", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "\346\270\251\345\272\246\357\274\232        \342\204\203", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "\346\265\267\346\213\224\357\274\232        m", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "\346\260\224\345\216\213\357\274\232        kPa", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "\347\205\247\345\272\246\357\274\232        klux", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "\351\243\216\351\200\237\357\274\232        m/s", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "\351\243\216\345\220\221\357\274\232", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        labelHumidity->setText(QCoreApplication::translate("MainWindow", "50", nullptr));
        labelTemperature->setText(QCoreApplication::translate("MainWindow", "25", nullptr));
        labelPressure->setText(QCoreApplication::translate("MainWindow", "101", nullptr));
        labelIllumination->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        labelWindSpeed->setText(QCoreApplication::translate("MainWindow", " 2", nullptr));
        labelAltitude->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        labelWindDirection->setText(QCoreApplication::translate("MainWindow", "\345\214\227", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "100%RH", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "-20", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "90", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "-200", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "45\342\204\203", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "110kPa", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "200klux", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "1000m", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "20m/s", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "\345\267\245\344\275\234\346\250\241\345\274\217", nullptr));
        radioButtonManualMode->setText(QCoreApplication::translate("MainWindow", "\346\211\213\345\212\250\351\207\207\351\233\206\346\250\241\345\274\217", nullptr));
        radioButtonAutoMode->setText(QCoreApplication::translate("MainWindow", "\350\207\252\345\212\250\351\207\207\351\233\206\346\250\241\345\274\217", nullptr));
        pushButtonGetHardwareData->setText(QCoreApplication::translate("MainWindow", "\350\257\273\345\217\226\346\265\213\351\207\217\346\225\260\346\215\256", nullptr));
        pushButtonGetRandomData->setText(QCoreApplication::translate("MainWindow", "\347\224\237\346\210\220\346\250\241\346\213\237\346\225\260\346\215\256", nullptr));
        pushButtonGetInputData->setText(QCoreApplication::translate("MainWindow", "\350\276\223\345\205\245\346\250\241\346\213\237\346\225\260\346\215\256", nullptr));
        groupBoxHTTP->setTitle(QCoreApplication::translate("MainWindow", "HTTP\351\200\232\344\277\241", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "\350\256\276\345\244\207ID\357\274\232", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "API-KEY\357\274\232", nullptr));
        groupBoxTCP->setTitle(QCoreApplication::translate("MainWindow", "TCP\351\200\232\344\277\241", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "\351\211\264\346\235\203\347\240\201\357\274\232", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "\350\256\276\345\244\207ID\357\274\232", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "\350\204\232\346\234\254\345\220\215\347\247\260\357\274\232", nullptr));
        pushButtonClearLog->setText(QCoreApplication::translate("MainWindow", "\346\270\205\347\251\272", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
